In [38]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
#import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Array

In [39]:
# 1D array
one_d=np.array([1,1,2,3])
print(one_d)
one_d.shape

[1 1 2 3]


(4,)

In [40]:
# 2D array
two_d=np.array([[1,1,2,3],[10,5,3,2]])
print(two_d)
two_d.shape

[[ 1  1  2  3]
 [10  5  3  2]]


(2, 4)

# Reshapping array

In [41]:
one_d.reshape(2,2)

array([[1, 1],
       [2, 3]])

In [42]:
one_d.reshape(4,1)

array([[1],
       [1],
       [2],
       [3]])

In [43]:
two_d.reshape(4,2)

array([[ 1,  1],
       [ 2,  3],
       [10,  5],
       [ 3,  2]])

In [44]:
two_d.reshape(8,1)

array([[ 1],
       [ 1],
       [ 2],
       [ 3],
       [10],
       [ 5],
       [ 3],
       [ 2]])

# Slicing

In [45]:
two_d[0:1]

array([[1, 1, 2, 3]])

In [46]:
two_d[0:1,1:3]

array([[1, 2]])

# Math operation

## Nean Median

In [47]:
print(one_d)
print("Mean",np.mean(one_d))

[1 1 2 3]
Mean 1.75


In [48]:
print(two_d)
print("Mean",np.mean(two_d))

[[ 1  1  2  3]
 [10  5  3  2]]
Mean 3.375


In [49]:
print(one_d)
print("Median",np.median(one_d))

[1 1 2 3]
Median 1.5


In [50]:
print(two_d)
print("Median",np.median(two_d))

[[ 1  1  2  3]
 [10  5  3  2]]
Median 2.5


## Min & Max

In [51]:
# Min & Max
print(two_d)
print("Min element",np.min(two_d))
print("Max elemet",np.max(two_d))

[[ 1  1  2  3]
 [10  5  3  2]]
Min element 1
Max elemet 10


In [52]:
print(two_d)
print("Min position",np.argmin(two_d))
print("Max Position",np.argmax(two_d))

[[ 1  1  2  3]
 [10  5  3  2]]
Min position 0
Max Position 4


## Quering (Searching)

In [53]:
print(one_d)
print("-----------Position where great than 1 -----------------")
x=np.where(one_d>1)
print(x)
print("=======>  elements greater than 1  <==========")
print(one_d[x])

[1 1 2 3]
-----------Position where great than 1 -----------------
(array([2, 3]),)
=======>  elements greater than 1  <==========
[2 3]


In [54]:
print(two_d)
print("-----------Position where great than 2 -----------------")
x=np.where(two_d>2)
print(x)
print("=======>  elements greater than 2  <==========")
print(two_d[x])

[[ 1  1  2  3]
 [10  5  3  2]]
-----------Position where great than 2 -----------------
(array([0, 1, 1, 1]), array([3, 0, 1, 2]))
=======>  elements greater than 2  <==========
[ 3 10  5  3]


## Filtering data

In [55]:
print(one_d)
fil_arr=one_d>2
print(fil_arr)
print(one_d[fil_arr])

[1 1 2 3]
[False False False  True]
[3]


## Sorting

In [56]:
a=np.array([[1,5,1,2,4]])
print(a)
print("After sorting")
print(np.sort(a))

[[1 5 1 2 4]]
After sorting
[[1 1 2 4 5]]


In [57]:
print(two_d)
print("After sorting")
print(np.sort(two_d))

[[ 1  1  2  3]
 [10  5  3  2]]
After sorting
[[ 1  1  2  3]
 [ 2  3  5 10]]


## Sum

In [58]:
print(one_d)
print(np.sum(one_d))

[1 1 2 3]
7


In [59]:
print(two_d)
print(np.sum(two_d))

[[ 1  1  2  3]
 [10  5  3  2]]
27


## Broadcasting

In [60]:
print(one_d)
print(np.add(one_d,5))

[1 1 2 3]
[6 6 7 8]


In [61]:
print(two_d)
print(one_d)
print("Add:",np.add(two_d,one_d))

[[ 1  1  2  3]
 [10  5  3  2]]
[1 1 2 3]
Add: [[ 2  2  4  6]
 [11  6  5  5]]
